services:
  reverse-proxy:
    image: traefik:v3.2
    # dit voegt extra opties toe aan het defaultcommando
    # in de Dockerfile voor Traefik staat "entrypoint"
    # dat deel is vast
    # dus het "command" bevat alleen de extra opstartopties
    # --api.insecure=true is nodig voor het dashboard
    # --providers.docker zegt Traefik info over andere containers te vragen aan Docker
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080" # web UI, kan door api.insecure=true
    volumes:
      # dit zorgt dat de Traefik instantie die zelf in Docker runt
      # Docker ook effectief kan contacteren
      - /var/run/docker.sock:/var/run/docker.sockdoc